import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        paper: {
          50: 'var(--paper-50)',
          100: 'var(--paper-100)',
          200: 'var(--paper-200)',
          300: 'var(--paper-300)',
          400: 'var(--paper-400)',
        },
        ink: {
          900: 'var(--ink-900)',
          800: 'var(--ink-800)',
          700: 'var(--ink-700)',
          500: 'var(--ink-500)',
          400: 'var(--ink-400)',
          300: 'var(--ink-300)',
          200: 'var(--ink-200)',
        },
        up: {
          700: 'var(--up-700)',
          500: 'var(--up-500)',
          300: 'var(--up-300)',
          50: 'var(--up-50)',
        },
        down: {
          700: 'var(--down-700)',
          500: 'var(--down-500)',
          300: 'var(--down-300)',
          50: 'var(--down-50)',
        },
        amber: {
          700: 'var(--amber-700)',
          500: 'var(--amber-500)',
          300: 'var(--amber-300)',
          50: 'var(--amber-50)',
        },
        accent: {
          900: 'var(--accent-900)',
          700: 'var(--accent-700)',
          500: 'var(--accent-500)',
          300: 'var(--accent-300)',
          50: 'var(--accent-50)',
        },
        viz: {
          1: 'var(--viz-1)',
          2: 'var(--viz-2)',
          3: 'var(--viz-3)',
          4: 'var(--viz-4)',
          5: 'var(--viz-5)',
          6: 'var(--viz-6)',
          7: 'var(--viz-7)',
        },
        rule: 'var(--rule)',
        'rule-strong': 'var(--rule-strong)',
        bg: 'var(--bg)',
        'bg-elevated': 'var(--bg-elevated)',
        'bg-raised': 'var(--bg-raised)',
        fg: 'var(--fg)',
        'fg-secondary': 'var(--fg-secondary)',
        'fg-tertiary': 'var(--fg-tertiary)',
        'fg-inverse': 'var(--fg-inverse)',
        link: 'var(--link)',
      },
      fontFamily: {
        display: 'var(--font-display)',
        editorial: 'var(--font-editorial)',
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        'display-1': 'var(--t-display-1)',
        'display-2': 'var(--t-display-2)',
        h1: 'var(--t-h1)',
        h2: 'var(--t-h2)',
        h3: 'var(--t-h3)',
        h4: 'var(--t-h4)',
        'body-lg': 'var(--t-body-lg)',
        body: 'var(--t-body)',
        small: 'var(--t-small)',
        caption: 'var(--t-caption)',
        micro: 'var(--t-micro)',
      },
      spacing: {
        's-1': 'var(--s-1)',
        's-2': 'var(--s-2)',
        's-3': 'var(--s-3)',
        's-4': 'var(--s-4)',
        's-5': 'var(--s-5)',
        's-6': 'var(--s-6)',
        's-7': 'var(--s-7)',
        's-8': 'var(--s-8)',
        's-9': 'var(--s-9)',
        's-10': 'var(--s-10)',
        's-11': 'var(--s-11)',
        's-12': 'var(--s-12)',
      },
      borderRadius: {
        'r-0': 'var(--r-0)',
        'r-1': 'var(--r-1)',
        'r-2': 'var(--r-2)',
        'r-3': 'var(--r-3)',
        'r-4': 'var(--r-4)',
        'r-pill': 'var(--r-pill)',
      },
      maxWidth: {
        container: 'var(--container)',
        narrow: 'var(--container-narrow)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        emphasis: 'var(--ease-emphasis)',
        exit: 'var(--ease-exit)',
      },
      transitionDuration: {
        fast: '140ms',
        base: '220ms',
        slow: '400ms',
        hero: '900ms',
      },
      boxShadow: {
        'ds-sm': 'var(--shadow-sm)',
        'ds-md': 'var(--shadow-md)',
        'ds-lg': 'var(--shadow-lg)',
        'ds-inset': 'var(--shadow-inset)',
      },
      letterSpacing: {
        tight: 'var(--tr-tight)',
        wide: 'var(--tr-wide)',
        eyebrow: 'var(--tr-eyebrow)',
      },
      lineHeight: {
        display: 'var(--lh-display)',
        tight: 'var(--lh-tight)',
        snug: 'var(--lh-snug)',
        body: 'var(--lh-body)',
        loose: 'var(--lh-loose)',
      },
    },
  },
  plugins: [],
};

export default config;
